services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: sail
        USER_ID: 1000
    image: getconnectx-app
    container_name: getconnectx-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # - /mnt/d/CODEVITS/Getconnectx.app:/var/www # Revision!
      - .:/var/www  # Mengarah ke folder tempat file yml berada.
    networks:
      - getconnectx
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: getconnectx-web
    restart: unless-stopped
    ports:
      # - "80:80"
      - "${APP_PORT:-80}:80" # Default 80, tapi bisa diganti lewat .env
    
    volumes:
      - ./:/var/www
      # - /mnt/d/CODEVITS/Getconnectx.app/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/ # Path relatif ke folder docker
    networks:
      - getconnectx
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: getconnectx-db
    restart: unless-stopped
    ports:
      # - "5432:5432"
      - "${DB_PORT:-5432}:5432" # Default 5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - getconnectx

  redis:
    image: redis:alpine
    container_name: getconnectx-redis
    restart: unless-stopped
    networks:
      - getconnectx

  mailpit:
    image: axllent/mailpit
    container_name: getconnectx-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - getconnectx

networks:
  getconnectx:
    driver: bridge

volumes:
  dbdata:
    driver: local
